name: 'Setup Node.js project'
description: 'Common first steps for Node.js GH actions jobs.'

inputs:
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    required: false
    default: '1'

outputs:
  package-dir:
    description: "Path under which node package lives. To be used as 'working-directory' for other steps."
    value: ${{ steps.find-package-dir.outputs.package-dir }}

runs:
  using: "composite"
  steps:

    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: 'Find package directory'
      id: find-package-dir
      shell: sh
      run: |
        # Take first package.json that we can find
        package_json="$( git ls-files ':(glob)**/package.json' | head -n1 )"
        if [ -z "$package_json" ]
        then
          echo "ERROR Failed to locate package.json."
          exit 1
        fi
        package_dir="$( dirname "$package_json" )"
        echo "Found package.json in '$package_dir'."
        echo "::set-output name=package-dir::$package_dir"

    - name: 'Read node.js version'
      id: node-version
      shell: sh
      env:
        PACKAGE_DIR: ${{ steps.find-package-dir.outputs.package-dir }}
      run: |
        ver_files=".node-version .nvmrc"
        for file in $ver_files
        do
          ver_file="$PACKAGE_DIR/$file"
          if [ -r "$ver_file" ]
          then
            break
          else
            unset ver_file
          fi
        done

        if [ -z "$ver_file" ]
        then
          echo >&2 "ERROR Failed to locate node.js version file. Tried: $ver_files (in $PACKAGE_DIR)"
          exit 1
        fi

        ver="$( sed 's/^v//' "$ver_file" )"
        if [ -z "$ver" ]
        then
          echo >&2 "ERROR Failed to read version number from $ver_file"
          exit 1
        else
          echo "Found version '$ver' in $ver_file"
        fi
        echo "::set-output name=value::$ver"

    - name: 'Cache node_modules'
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          ~/.cache/Cypress
        key: |
          modules-node-${{ runner.os }}-${{ steps.node-version.outputs.value }}-${{ hashFiles('**/package-lock.json') }}_${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          modules-node-${{ runner.os }}-${{ steps.node-version.outputs.value }}-${{ hashFiles('**/package-lock.json') }}_${{ hashFiles('**/yarn.lock') }}
          modules-node-${{ runner.os }}-${{ steps.node-version.outputs.value }}-

    - name: 'Setup node'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ steps.node-version.outputs.value }}

    - name: 'Install Yarn'
      shell: sh
      run: |
        if ! command -v yarn >/dev/null
        then
          npm install -g yarn
        fi

    - name: 'Install modules'
      shell: sh
      working-directory: ${{ steps.find-package-dir.outputs.package-dir }}
      run: |
        if [ -r "package-lock.json" ]
        then
          npm install
        elif [ -r "yarn.lock" ]
        then
          yarn install --frozen-lockfile
        else
          echo >&2 "ERROR No package lock file found."
          exit 1
        fi
